- name: Clean pg_hba.conf but keep comments
  become: true
  shell: |
    awk '/^\s*#/ || /^\s*$/' {{ data_mount_point }}/pgdata/pg_hba.conf > /tmp/pg_hba_cleaned
    mv /tmp/pg_hba_cleaned {{ data_mount_point }}/pgdata/pg_hba.conf
  args:
    executable: /bin/bash

- name: Append secure cluster access to pg_hba.conf
  become: true
  blockinfile:
    path: "{{ data_mount_point }}/pgdata/pg_hba.conf"
    block: |
      local all all scram-sha-256
      host replication {{ patroni_replication_user }} 127.0.0.1/32 scram-sha-256
      {% for host in groups['postgresql'] %}
      host replication {{ patroni_replication_user }} {{ hostvars[host]['private_ip'] }}/32 scram-sha-256
      host all all {{ hostvars[host]['private_ip'] }}/32 scram-sha-256
      {% endfor %}
      host all all 127.0.0.1/32 scram-sha-256
      host all all ::1/128 scram-sha-256
      host all all 10.0.0.0/16 scram-sha-256
      {% if control_node_ip is defined %}
      host all all {{ control_node_ip }}/32 scram-sha-256
      {% endif %}
  when: inventory_hostname in groups['postgresql']
